### ISSUE TITLE
Won't Start as Expected on Windows

### ISSUE THREAD

**Issue by krismeister** [apache/incubator-annotator#104]
On a windows machine the webpack module resolver does not respect the slashes as expected.

## Example:

```
yarn start 
......
ERROR in ./demo/index.js
Module not found: Error: Can't resolve 'C:\Users\username\projects\incubator-annotator-master\incubator-annotator-master\packagesdom\src\index.ts' in 'C:\Users\username\projects\incubator-annotator-master\incubator-annotator-master\web\demo'
 @ ./demo/index.js 27:0-288 91:23-53 92:26-59 93:19-49 186:30-44 232:19-39 241:19-36
 @ multi ./demo/index.html ./demo/index.js
```

## Expected Fix:
The project can build on windows the same as other platforms.

Here is the recommended fix I could find:
https://github.com/tleunen/babel-plugin-module-resolver/issues/242#issuecomment-350488615

**Comment by tilgovi** [comment]
Closed by #105.
