### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator#11]
I just successfully ran the demo with node 7.10.0 and npm 4.2.0

However, I've not yet attempted the hot-reload stuff.

@tilgovi are there specific things that node 8 and npm 5 enable that I'm missing?

**Comment by tilgovi** [comment]
I just didn't want to moderate my use of ES2017. The only script is `bin/start.mjs`, though, which is pretty simple.

I'll address this issue as soon as I can. Probably, I should re-introduce babel into the pipeline and formalize the build targets and developer runtime requirements.
