### ISSUE TITLE
I'm not getting the text position

### ISSUE THREAD

**Issue by raphael10-collab** [apache/incubator-annotator#128]
The text is highlighted but I do not get the text position, needed for further annotating

![image](https://user-images.githubusercontent.com/70313067/187079466-224a78d1-8b7c-4787-9057-5e8934e5262f.png)

![image](https://user-images.githubusercontent.com/70313067/187079636-ba6c4013-b6d6-439f-a4d5-6fcae28459fc.png)

This is the code I'm using:

    // https://annotator.apache.org/docs/getting-started/
    
    import { describeTextQuote } from '@apache-annotator/dom'
    import { createTextQuoteSelectorMatcher, highlightText } from '@apache-annotator/dom';
    
    async function describeCurrentSelection() {
      const userSelection = window.getSelection()?.getRangeAt(0);
    
      console.log("view-preload.ts-userSelection: ", userSelection)
    
      if (!userSelection || userSelection.isCollapsed) return;
    
      console.log("view-preloads-describeTextQuote(userSelection): ", describeTextQuote(userSelection))
    
      return describeTextQuote(userSelection);
    }
    
    async function highlightSelectorTarget(textQuoteSelector) {
      const matches = createTextQuoteSelectorMatcher(textQuoteSelector)(document.body);
    
      console.log("view-preload.ts-highlighSelectorTarger-matches: ", matches)
    
      // Modifying the DOM while searching can mess up; see issue #112.
      // Therefore, we first collect all matches before highlighting them.
      const matchList = [];
      for await (const match of matches) matchList.push(match);
    
      for (const match of matchList) highlightText(match);
    }
    
    
    document.addEventListener('mouseup', async () => {
    
      const selector = await describeCurrentSelection();
      const existingSelectors = JSON.parse(localStorage[document.URL] || '[]');
      localStorage[document.URL] = JSON.stringify([...existingSelectors, selector]);
      await highlightSelectorTarget(selector);
    })
    
    // Highlight the last selection that was stored, if any.
    async function highlightStoredSelectors() {
      if (localStorage[document.URL]) {
        const selectors = JSON.parse(localStorage[document.URL]);
        for (const selector of selectors) {
          console.log("view-preload.ts-highlightStoredSelectors-selector: ", selector)
          await highlightSelectorTarget(selector);
        }
      }
    }
    highlightStoredSelectors()
    
    
    window.addEventListener('mouseup', (e) => {
      if (e.button === 3) {
        e.preventDefault();
        goBack();
      } else if (e.button === 4) {
        e.preventDefault();
        goForward();
      }
    });

**Comment by Treora** [comment]
A quick response, as I (nor others, it seems) get around to look further at your issue. From your description it’s not clear to me what you mean. If you mean to create a TextPositionSelector, see the [describeTextPosition](https://annotator.apache.org/docs/api/modules/dom.html#describetextposition). Best to get the position of the selection before highlighting it (if you do both), because the highlighter will modify the dom and thereby the selection.
If you mean position as in coordinates on the page, you can get those from the browser’s APIs, e.g. [`Range.getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Range/getBoundingClientRect). I hope that helps.
