### ISSUE TITLE
@apache-annotator/dom not updated on NPM

### ISSUE THREAD

**Issue by pkspyder007** [apache/incubator-annotator#142]
The current version of @apache-annotator/dom v0.2.0 still uses optimal-select which was fixed in PR #117 
Is this project still active or one using it should seek forking it or alternatives?

**Comment by pkspyder007** [comment]
I'll be happy to work on the project to fix stuff and learn more about it.

**Comment by Treora** [comment]
Hi!

The numbered versions on npm indeed lag far behind the main branch. As an incubating Apache project, each official release needs to be verified and upvoted by three team members (’committers’), and also by project mentors. We’ve had too few actively involved people to smoothly publish releases..

You may want to try the `dev` tag on npm instead; it corresponds directly to the main branch. See https://annotator.apache.org/docs/getting-started/

> Is this project still active or one using it should seek forking it or alternatives?

It’s active in the sense that it is not abandoned, but us core developers have hardly gotten around to work on it lately. We’d be happy if others join the effort, or continue with it in other ways if they prefer.

> I'll be happy to work on the project to fix stuff and learn more about it.

Feel free!

**Comment by reckart** [comment]
Once a new release is done, it will be published to npmjs. Meanwhile, there is nothing to be done here.
