### ISSUE TITLE
Firefox selection weirdness in the demo

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator#16]
When I select content in the left-hand box in the demo, the selection jumps outside of the box and sometimes leaves earlier selections in place. Double clicking a word works fine, however.

Also, if I double click near the `,` or `.` in the sentence the highlighting happens within the scope of the whole page--not just within the right-hand side box.

Chrome does seem to have these issues.

This trouble is in Firefox Dev Edition 57.0b12 (64-bit).

**Comment by tilgovi** [comment]
I can't reproduce this in the same environment.

I'll close this for now, but am happy to work this out with you if it continues to be a problem.

**Comment by BigBlueHat** [comment]
Here's what it looks like for me after double-clicking the first `,` in the selection area. You'll note in this case it *does* properly highlight the matching `, ` (the space gets added by the browser's handling of double-clicking text) in the display box, but then it also selects the `, ` in the content below (see the gray highlight after "In the second paragraph").

![screenshot-2017-11-14 apache annotator incubating demo](https://user-images.githubusercontent.com/43209/32783664-88fa74b8-c91a-11e7-87c4-7ee71e2a5dcd.png)

**Comment by BigBlueHat** [comment]
Double clicking the `.` at the end of the sentence shows the same situation--the highlight appearing in the content below the demo boxes. However, it does not display in the `#corpus` (right hand side display box) because on the left the text contains a `\n` but on the right that `\n` gets stripped (afaict) by the use of `innerText` when rendering the display.

![screenshot-2017-11-14 apache annotator incubating demo 1](https://user-images.githubusercontent.com/43209/32783754-d8b85b46-c91a-11e7-8e0c-5e9ec2bd5c2c.png)

The whitespace thing should be relatively trivial to fix, but the selecting outside of the intended area is probably a bug.

**Comment by Treora** [comment]
@BigBlueHat: just to check, might you have the [Precise links](https://addons.mozilla.org/en-US/firefox/addon/precise-links/) extension enabled? That could surely cause the out-of-box selection (it reacts to the fragment identifier, and applies it to the page as a whole).

**Comment by BigBlueHat** [comment]
@Treora I did indeed (at least in Firefox). Thank you!

That was indeed the cause, as disabling it removed the "bug."

Thanks, Gerben!
