### ISSUE TITLE
Adding the demo to the site

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator#18]
Right now the demo in this repo is as much a dev environment as it is a demo--which is great! 😸 

However, I'd also like to package up the demo code (occasionally) and add it to the [apache/incubator-annotator-website](https://github.com/apache/incubator-annotator-website) repo.

I'm new to webpack, so untangling the dev/build environment bits is what I need guidance in.

Thanks!
🎩

**Comment by JakeHartnell** [comment]
Working on it!

**Comment by JakeHartnell** [comment]
I added a webpack build to the incubator-annotator-website. It includes the demo from here, but styles it with Semantic UI. Going to be working on adding code examples to the demo page as that would be the most helpful for people getting started.

PR here: https://github.com/apache/incubator-annotator-website/pull/3

**Comment by JakeHartnell** [comment]
Perhaps this should be closed after this PR: https://github.com/apache/incubator-annotator-website/pull/4

There are still more improvements to be made. For example, it would be nice if there were code examples next to the demos. Maybe we should create a separate issue for code examples?

**Comment by BigBlueHat** [comment]
@JakeHartnell a code example focused issue would be grand! Would also serve as some basic docs/tests. Great idea.
