### ISSUE TITLE
[incubator-annotator] capitalization error in imported module name asyncGenerator 

### ISSUE THREAD

**Issue by uskudarli** [apache/incubator-annotator#19]
After installation of [incubator-annotator](https://github.com/apache/incubator-annotator)

when the demo is started
> yarn start
the error:
ERROR in ./node_modules/@babel/runtime/helpers/builtin/es6/wrapAsyncGenerator.js
Module not found: Error: Can't resolve './AsyncGenerator' 
is encountered.

Fixing the capitalization (from A to a) resolves the issue (import AsyncGenerator from "./asyncGenerator")

**Comment by tilgovi** [comment]
Look like @bjonnh diagnosed this is #20. I'm going to close this so we can track it in one place. Thanks so much!

**Comment by tilgovi** [comment]
This should be fixed now!
