### ISSUE TITLE
Upstream bug in babel?

### ISSUE THREAD

**Issue by bjonnh** [apache/incubator-annotator#20]
I had to edit node_modules/\@babel/runtime/helpers/builtin/es6/wrapAsyncGenerator.js
and change the AsyncGenerator.js include to asyncGenerator.js

I couldn't find that in the original babel code, they seem to use a generator.

Filed a bug upstream: https://github.com/babel/babel/issues/6938

I

**Comment by tilgovi** [comment]
Thank you! That does look like an upstream bug.

**Comment by tilgovi** [comment]
I think I might disable the runtime transformation for now. I'm having some other issues with it, too.

**Comment by BigBlueHat** [comment]
Cool. I'll close this as needing to be upstreamed. @bjonnh you up for doing that? 😄

**Comment by tilgovi** [comment]
This should be fixed now!
