### ISSUE TITLE
Incorporate Web Annotation testing tools

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator#31]
This will ease testing (by us or others) of the Web Annotation JSON documents that we (and others) pass to the client libraries we're currently building.

There are several repos which contain code we can use:

#### Web Annotation Data Model
* https://github.com/w3c/web-annotation-tests - The JSON Schema's built by the Web Annotation WG
* https://github.com/web-platform-tests/wpt/tree/master/annotation-model - The JSON Schema's also exist in the Web Platform Tests tooling (identical to the above, but surrounding tools have changed a bit)

#### Web Annotation Protocol
* https://github.com/web-platform-tests/wpt/tree/master/annotation-protocol - contains...
  * https://github.com/web-platform-tests/wpt/blob/master/annotation-protocol/server/server-manual.html - client-side tests run against a configurable protocol server endpoint
  * https://github.com/web-platform-tests/wpt/blob/master/annotation-protocol/tools/protocol-server.py - Python 2 / wptserve-based reference implementation
  * https://github.com/web-platform-tests/wpt/tree/master/annotation-protocol/files - files served by the reference implementation
* https://github.com/BigBlueHat/web-annotation-protocol-server - the original source for the reference implementation
* https://github.com/BigBlueHat/web-annotation-protocol-tester - command line protocol (and contained format) testing tool--*incomplete*

#### Web Annotation Vocab
* https://github.com/web-platform-tests/wpt/tree/master/annotation-vocab - vocabulary (non-serialization-specific) testing of the output graphs and term usage

All of these are licensed such that we can incorporate them into this code. The command line protocol tester (which uses mocha.js) is probably the thing of most interest for us--especially if we expand it to use the JSON Schema's which are used for W3C validation.

**Comment by BigBlueHat** [comment]
Plan confirmed with @tilgovi to create a validation tool in `scripts/` as a command line tool (using mocha.js) built from https://github.com/BigBlueHat/web-annotation-protocol-tester + the JSON Schema's from https://github.com/w3c/web-annotation-tests

End game will be a script that validates local JSON or JSON from a URL against the Web Annotation Data Model JSON Schemas.

**Comment by JCCR** [comment]
I can work on this.

**Comment by BigBlueHat** [comment]
@JCCR awesome! Would love your help. I'm getting the basics in today, I hope, but let's chat! Find me in `#annotator` on Freednode if you're available today. Otherwise, let's work here async. 😸

**Comment by JCCR** [comment]
@BigBlueHat
Can do asynchronously!
Would have liked to jump in and chat but I'm AFK today.

**Comment by BigBlueHat** [comment]
@JCCR PR #32 will *technically* close this issue, however, there's much more room here for improving this code.

It currently only works on files (despite the `--url` name of the parameter), it needs more of the available schemas incorporated, it might be nice to have it work on a folder (or Collection!) of annotations. Etc. 😃 

Feel free to bring your inspiration and ideas to any of this work!

**Comment by tcole3** [comment]
The schemas at https://github.com/w3c/web-annotation-tests conform to draft-04 of json schema. draft-07 (http://json-schema.org/specification.html) is the current version. Schemas were developed almost 2 years ago using then current versions of node.js and ajv  (another json validator - https://www.npmjs.com/package/ajv). Updating to newer version of json schema will allow some simplifications (avoid, for example, double negatives when checking arrays). 

Please note the reliance on 'referenced' schemas, i.e., the actual schema confirming that an annotation meets a requirement of the Web Annotation Data Model typically relies on 2 or 3 referenced schemas which live in different file(s) and are shared across multiple schemas (https://github.com/w3c/web-annotation-tests/tree/master/definitions). Ajv makes it easy to load referenced schemas asynchronously (https://www.npmjs.com/package/ajv#asynchronous-schema-compilation). 

Also, there are known to be mistakes in 2 or 3 of the schemas (will pass an incorrect annotation or fail a correct annotation), but these only show up in truly edge cases of the data model and will be easy to fix at a later time. 

I'm not currently a committer on annotator-incubator, but happy to help if any questions about the schemas themselves or if there's anything else I can help with. Happy also to take another run at my management to get approvals necessary to be added as a committer for the incubator. 

@BigBlueHat sounds like Saturday hack work went well. Sorry I couldn't stick around for it.
