### ISSUE TITLE
Make test `--url` parameter work with remote URLs (not just local files)

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator#33]
Maybe use [requests](https://www.npmjs.com/package/requests) or [axios](https://www.npmjs.com/package/axios) or Node's [http](https://nodejs.org/api/http.html#http_http).

Preference?

**Comment by BigBlueHat** [comment]
@JCCR you're welcome to snag this one if you'd like! 😁

**Comment by jccr** [comment]
@BigBlueHat 
Yes. I've been meaning to contribute to the project, but I needed this reminder. Give me a week and if you don't hear back from me by then.. I don't want to stop someone else from contributing.
