### ISSUE TITLE
RFC: Use standard-version

### ISSUE THREAD

**Issue by tilgovi** [apache/incubator-annotator#44]
https://github.com/conventional-changelog/standard-version

**Comment by BigBlueHat** [comment]
As long as this doesn't further slow our coding on our actual project, I'm all in. 😉

**Comment by tilgovi** [comment]
I changed my mind. I propose we close this issue an not worry so much about automating every little thing until we actually make releases often enough that we feel that pain.

**Comment by BigBlueHat** [comment]
Agreed. This one can wait.
