### ISSUE TITLE
Generate accessible annotations

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator#45]
It's being explored here:
https://github.com/w3c/aria/issues/749

We can help by implementing the markup generation, etc.

**Comment by BigBlueHat** [comment]
There's recent discussion here for those who want to follow along there and/or sign-up for that list:
https://lists.w3.org/Archives/Public/public-aria/2018Oct/0016.html

**Comment by Treora** [comment]
Superseded by #53? Closing. (also, I added this topic to the new [Tech Radar](https://github.com/apache/incubator-annotator/wiki/Tech-Radar) page on the wiki)
