### ISSUE TITLE
Explore WorkerDOM

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator#49]
[WorkerDOM](https://github.com/ampproject/worker-dom#workerdom) is part of the growing list of [AMP Project](https://github.com/ampproject/) open source and potentially standardized outputs.

This one in particular could be useful for highlighting implementations:
> Use Cases:
> 1.    Embedded content from a third party living side by side with first party code.
> 2.    Mitigation of expensive rendering for content not requiring synchronous updates to user actions.
> 3.    Retaining main thread availablity for high priority updates by async updating elsewhere in a document.

**Comment by Treora** [comment]
I added this to the new [Tech Radar](https://github.com/apache/incubator-annotator/wiki/Tech-Radar) page on the wiki; updates can be added there, and discussion may also continue in this issue; but I will close it as there is no current activity on this and no particular action to take.
