### ISSUE TITLE
Range Normalization

### ISSUE THREAD

**Issue by tilgovi** [apache/incubator-annotator#51]
We're currently using the `range-normalize` in the `describeTextQuoteByRange` function. This package is useful, but I once submitted a complete rewrite that has no external dependencies: https://github.com/webmodules/range-normalize/pull/2

I would like to pull that into tree.

**Comment by BigBlueHat** [comment]
@tilgovi please do bring in this rewrite. We can make it available as it's own module for others to use as well.

**Comment by tilgovi** [comment]
Will do.

**Comment by tilgovi** [comment]
As this dependency was removed in c7e98eeac3e07e45b14b94e2aec2add8f137aea9, I am going to defer this decision for a while.

**Comment by tilgovi** [comment]
I'll close this for now, as it seems like we may not need this at the moment.
