### ISSUE TITLE
Highlight API explainer

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator#54]
Proposed API explainer from the Edge team:
https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/highlight/explainer.md

This would make a huge difference for building out any highlight/selection-representation system--especially because it handles the "hard stuff" mentioned in #22.

**Comment by Treora** [comment]
Current home seems to be: https://drafts.csswg.org/css-highlight-api-1/

I added this topic to the new [Tech Radar](https://github.com/apache/incubator-annotator/wiki/Tech-Radar) page on the wiki; updates can be added there, and discussion may also continue in this issue; but I will close it as there is no current activity on this and no particular action to take.
