### ISSUE TITLE
Consider exploring Intl.Segmenter (and current polyfill) for word-based selection

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator#55]
This proposal (and its current polyfill) attempt to standardize Unicode word segmentation: 
https://github.com/tc39/proposal-intl-segmenter

As I recall this was something both the Web Annotation WG and Hypothes.is (at least) struggled with determining the best method of handling due to JavaScript's sub-par Unicode support "back then." This, perhaps, will improve that situation at least in terms of segmentation.

**Comment by tilgovi** [comment]
See also WICG/ScrollToTextFragment#42

**Comment by Treora** [comment]
I added this topic to the new [Tech Radar](https://github.com/apache/incubator-annotator/wiki/Tech-Radar) page on the wiki; updates can be added there, and discussion may also continue in this issue; but I will close it as there is no current activity on this and no particular action to take.
