### ISSUE TITLE
Sort out LICENSE and NOTICE issues from v0.1.0-rc.2

### ISSUE THREAD

**Issue by tilgovi** [apache/incubator-annotator#63]
Vote thread for context: https://lists.apache.org/thread.html/r537b1189041fcd063e44859607e1ed5a5ed0f569cda4fcbee03fc5ed%40%3Cgeneral.incubator.apache.org%3E

If the things mentioned in our NOTICE file are actually included in our code, it sounds like we should move the full licenses to our LICENSE file. If not, we should remove them from our NOTICE file. A double check on ASF policies around what goes where is in order.

**Comment by jccr** [comment]
Is there a convention/policy within Apache's to allow for a `LICENSE-3RD-PARTY` file? Would that help with the separation of dependency licenses from the main project's license?

**Comment by tilgovi** [comment]
I think the process is to append it to LICENSE. Here's the documentation: http://www.apache.org/dev/licensing-howto.html

**Comment by BigBlueHat** [comment]
Getting this in order now. I'd been using https://github.com/apache/couchdb/blob/master/NOTICE for reference...not realizing that https://github.com/apache/couchdb/blob/master/LICENSE also had more... It's becoming clearer...with time. 😃

**Comment by BigBlueHat** [comment]
Not sure why this didn't auto-close, but this is completed in #66.
