### ISSUE TITLE
Document release process and release testing process

### ISSUE THREAD

**Issue by tilgovi** [apache/incubator-annotator#64]
Write down, in the GitHub project wiki, the steps for making a release and testing a release, to ease release management and voting.

**Comment by Treora** [comment]
I suppose this is finished. On the wiki: [Creating a Release](https://github.com/apache/incubator-annotator/wiki/Creating-a-Release) and [Testing a Source Release](https://github.com/apache/incubator-annotator/wiki/Testing-a-Source-Release).
