### ISSUE TITLE
Make the purpose of this tool clear(er)

### ISSUE THREAD

**Issue by miclill** [apache/incubator-annotator#7]
I can't find a good description of the problem this is trying to solve.

**Comment by BigBlueHat** [comment]
Sorry for the delayed response!

I'm guessing that http://annotator.apache.org/ was insufficient? 😃 

We're focused first on building browser libraries for working with [Web Annotation Data Model](https://www.w3.org/TR/annotation-model/) documents. We're also aggregating community members and code for [Web Annotation Protocol](https://www.w3.org/TR/annotation-protocol/) and model validation tooling.

Our primary objective is to provide *developers* with a set of "front to back" libraries for working with Web Annotation.

Does that summarize it all a bit better? If not, I'd love to hear more!

Thanks!
🎩

**Comment by miclill** [comment]
@BigBlueHat thank you for your answer. I understand better now. May I suggest to add an example to http://annotator.apache.org/? I think a lot of people are like me and really like examples.

**Comment by BigBlueHat** [comment]
@miclill glad that was helpful. 😄  We've got a demo in this repo now, and I do plan to get it added to the web site--along with more docs/info soon.

Appreciate the interest! Be sure to say "hi" on the mailing list: http://annotator.apache.org/#mailing-lists
