### ISSUE TITLE
Add composer.json to let PHP developers to keep track of annotator.js on packagist.org

### ISSUE THREAD

**Issue by fabiomontefuscolo** [apache/incubator-annotator#8]
Hello!

I would like to propose the composer.json file and ask you to add you library on packagist.org. It will be easy to PHP developer keep track of your updates and refer your library as project dependency. I bet many CMS and blogs developers would take advantage of this facility.

Unfortunately, all I can do is propose this file. If you agree, you have more 3 steps:

i) create packagist.org account;
ii) submit your package and
iii) wire github webhooks in packagist

I would love to have your library on packagist.org

**Comment by tilgovi** [comment]
This is not the annotator.js project and we are not ready for anyone to consume it yet.

**Comment by marclaporte** [comment]
Hi Randall,

FYI, it was also submitted here:
https://github.com/openannotation/annotator/pull/661

Context: We added annotator.js v1.2 to Tiki 17.0: https://doc.tiki.org/Tiki17#Annotations and we want to get everything from Packagist to make our lives easier and to increase mindshare.

And now, we are wondering what we should do for Tiki 18.x and beyond. Should we plan to upgrade to v2? ( but it's alpha and I see no plan for an official release ). Will there be a migration path to Apache Annotator?, etc. Realistically, what timeline are we looking at?  I really don't want this to be perceived as pressure. Just looking for best possible information so we can plan what will be in our next releases.
https://tiki.org/Versions

Thanks!

**Comment by tilgovi** [comment]
You are more than welcome to publish whatever you like to composer, but I have no experience with it and no desire to make an account or maintain and commit to publishing there. The first focus here is on making an official release of any kind at all. At that point, I imagine we'd publish bundled .js that you could vendor, just as you're vendoring other libraries, or you could push it to composer if you prefer to consume it from there.

If publishing this to composer is something you feel very strongly about we could make a packaging repository and add you as a committer to maintain things there. I don't think it makes sense to clog up this repo with packaging boilerplate for every package repository that someone wants to get annotator from.

As for what to do with Tiki and annotator.js, I can't say yet. I don't have time to work on this and annotator.js right now. I have thought about rebooting Annotator.js as an application built on the Apache Annotator libraries, but we're not there yet and Annotator.js probably needs new maintainers for this to happen.
