### ISSUE TITLE
update version of npm packages

### ISSUE THREAD

**Issue by mokipedia** [apache/incubator-annotator#82]
Hi,
the npm releases seem to be a little behind the releases marked here in github.
Is there a new release planned?

**Comment by tilgovi** [comment]
We have stopped publishing pre-release versions for the moment, as we are getting our release process in order. The first official release is v0.1.0, which was tagged less than 24 hours ago. I am waiting 24 hours for the tarball to propagate to appear on Apache mirrors before I send a release announcement and publish to npm.

**Comment by tilgovi** [comment]
The release is now live. Thank you for your patience!

There is no formal documentation at the moment, so please dig into the code and raise questions on the mailing list or in GitHub issues. We are very interested in getting feedback and helping people get started working with the project and contributing.
